export default {
    products:[
        {
            _id:"1",
            name:"Slim Fit Shirt",
            category:"Shirts",
            image:"./Images/shirt-tie.jpg",
            price:20,
            brand: "Westside",
            description: "It's a nice shirt",
            rating:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id:"2",
            name:"Casual Shirt",
            category:"Shirts",
            image:"./Images/shirt-white.jpg",
            description: "It's a nice shirt",
            price:30,
            brand: "Westside",
            rating:4.5,
            numReviews:9,
            countInStock:4,
        },
        {
            _id:"3",
            name:"Slim Fit Shirt",
            description: "It's a nice shirt",
            category:"Shirts",
            image:"./Images/shirt-tie.jpg",
            price:20,
            brand: "Westside",
            rating:4.5,
            numReviews:3,
            countInStock:0,
        },
        {
            _id:"4",
            name:"Slim Fit Shirt",
            category:"Shirts",
            description: "It's a nice shirt",
            image:"./Images/shirt-tie.jpg",
            price:60,
            brand: "Westside",
            rating:4.5,
            numReviews:6,
            countInStock:2,
        },
        {
            _id:"5",
            name:"Casual Shirt",
            description: "It's a nice shirt",
            category:"Shirts",
            image:"./Images/shirt-white.jpg",
            price:30,
            brand: "Westside",
            rating:4.5,
            numReviews:3,
            countInStock:6,
        },
        {
            _id:"6",
            name:"Jeans",
            image:"./Images/levis-pant.jpg",
            description: "It's a nice Jeans",
            price:40,
            brand: "Levis",
            rating:3.9,
            numReviews:10,
            countInStock:3,
        },
       
    ]
}